config/routes.rb
Rails.application.routes.draw do
  root :to => 'categories#index'
  resources :categories do
    resources :transactions
    resources :incomes
  end
  resources :transactions
  resources :incomes

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :transactions, dependent: :destroy
	has_many :incomes, dependent: :destroy
	validates :name, presence: true
end

app/models/income.rb
class Income < ActiveRecord::Base
	validates :name, presence: true
    validates :amount, presence: true
	belongs_to :category
	# def income
	# 	@income
	# end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :category
  validates :name, presence: true
  validates :amount, presence: true
  validates :category, presence: true
  # def amount
  # 	@amount
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @transactions = Transaction.where(:category_id => 1).all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
    @categories = Category.all
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    # @income = Income.new(income_params)
    @income = Category.find(params[:income][:category_id]).incomes.create(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:name, :amount, :category_id)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
    
  # if !params.has_key?(:category_id)
  #    @category = Category.find(params[:category_id])
  #    @transactions = Category.find(params[:category_id]).transactions
  #  end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @categories = Category.all
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
  
    # category_id = (params[:category_id]) or params[:transaction][:category_id]
    @transaction = Category.find(params[:transaction][:category_id]).transactions.create(transaction_params)
    # if !params.has_key? (category_id)
    # @categories = Category.all
    # end
    # Income.first.amount - @transaction.amount
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    byebug
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:name, :amount, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group col-sm-3'>
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn-group' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="section-container light-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                 <h2 style="text-align:center;">Categories</h2>
                 <h4 style="text-align:center;">Save you money</h4>
            </div>
      <% @categories.each do |category| %>
            <div class="col-md-3 light-panel">
              <div class='inner'>
                <td><%= link_to ''+category.name, category  %></td><br/><br/>
                <td><%= link_to 'Edit', edit_category_path(category) %></td>
                <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </div>
            </div>  <% end %>
       <div class="col-md-3 light-panel">
        <%= link_to 'New Category', new_category_path %>
       </div>
        </div>
    </div>
</div>

app/views/categories/new.html.erb
<div class="section-container light-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                 <h2 style="text-align:center;">Create New Category</h2>

                 <h4 style="text-align:center;">Save your money</h4>
            </div>
            <div class="col-md-3 light-panel">
                <div class='inner'>
                      <%= render 'form' %>
                      <%= link_to 'Back', categories_path, :class => 'glyphicon glyphicon-arrow-left' %>
                </div>
            </div>
        </div>
    </div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="section-container light-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                 <h2 style="text-align:center;">Categories</h2>
                 <h4 style="text-align:center;">Save you money</h4>

            </div>
            <div class="col-md-8 light-panel">
                <div class='inner'>
                    <p><strong><%= @category.name %> </p> <br/>
                    <%= link_to 'Edit', edit_category_path(@category) %> |
                    <%= link_to 'Back', categories_path %>  
                </div>
            </div>       
        </div>
    </div>
    
    

app/views/incomes/_form.html.erb
<%= form_for(@income) do |form| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :amount %><br>
    <%= form.text_field :amount %>
  </div>
  <% if !@categories.nil? %>
  <div class="field">
    <%= form.label :category_id %><br>
    <%= form.collection_select :category_id, @categories, :id, :name, :include_blank => false %> 
  </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="section-container light-bg">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                 <h2 style="text-align:center;">Income Source</h2>
                 <h4 style="text-align:center;">Save you money</h4>
            </div>
            
             <div class="col-md-12 light-panel">
                <div class='inner'>
                  <table>
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Amount</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @incomes.each do |income| %>
                        <tr>
                          <td><%= income.name %></td>
                          <td><%= income.amount %></td>
                          <td><%= link_to 'Show', income %></td>
                          <td><%= link_to 'Edit', edit_income_path(income) %></td>
                          <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
            </div>
            <div class="col-md-3 light-panel">
                <div class='inner'>
                    <%= link_to 'New Income', new_income_path %>
                </div>
            </div>

        </div>
    </div>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="section-container light-bg">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                 <h2 style="text-align:center;">Income Source</h2>
                 <h4 style="text-align:center;">Save you money</h4>
            </div>
            
            <div class="col-md-12 light-panel">
                <div class='inner'>
                <p><strong>Name: <%= @income.name %></p> 
                <p><strong>Amount: <%= @income.amount %></p> 
                </div>
            </div>
             <div class="col-md-3 light-panel">
                <div class='inner'>
                    <%= link_to 'Edit', edit_income_path(@income) %> |
                    <%= link_to 'Back', incomes_path %>
                </div>
            </div>
        </div>
    </div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <% if !@categories.nil? %>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, @categories, :id, :name, :include_blank => false %> 
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.name %></td>
        <td><%= transaction.amount %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @transaction.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>